- name: pacotes classroom
  apt:
    update_cache: yes
    pkg:
      - build-essential
      - cmake
      - curl
      - git
      - jq
      - kbibtex
      - kile
      - kile-l10n
      - octave
      - python3-pip
      - r-cran-rcmdr
      - r-recommended
      - spyder
      - texlive-latex-recommended
      - texmaker
      - texstudio

- name: install rstudio
  apt:
    deb: https://download1.rstudio.org/electron/jammy/amd64/rstudio-2025.05.1-513-amd64.deb

- name: install automirror
  apt:
    deb: https://github.com/schlomo/automirror/releases/download/v49/automirror_49_all.deb

- name: adiciona usuário aula
  user:
    name: aula
    password: '{{ classroom_user_password }}'
    append: yes
    groups:
      - audio
      - bluetooth
      - netdev
      - plugdev
      - scanner
      - video
    shell: /bin/bash

- name: configura autologin
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#autologin-user='
    line: autologin-user=aula

- name: configura screensaver
  copy:
    src: dconf/screensaver
    dest: /etc/dconf/db/local.d/01-screensaver
  notify: dconf update

- name: configura automirror
  file:
    src: /usr/share/applications/automirror.desktop
    dest: /etc/xdg/autostart/automirror.desktop
    state: link
